import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import NextAuthProvider from "@/components/providers/next-auth.provider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import RootNavbar from "@/components/root-navbar";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className}`}>
        <NextAuthProvider>
          <RootNavbar />
          <div className="mt-[3.15rem] px-1">{children}</div>
          <div className="mt-5">
            <Footer />
          </div>
        </NextAuthProvider>
        <ToastContainer autoClose={2000} />
      </body>
    </html>
  );
}
